version: '3.9'
services:
  de_postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "orders"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: returns
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"


  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: always
    volumes:
      - ./clickhouse/data/:/var/lib/clickhouse


  metabase:
    build: 
      context: .
      dockerfile: ./metabase/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - metabase-data:/metabase-data


volumes:
  mysqldb:
  postgresdb:
  metabase-data:

networks: 
  default:
    external:
      name: external-de
